# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6c9485bccfbab8317d9684b7af7903cdddb2806931f77bf745ad2be82a02808ae047d317a86aefb9f4a810d0439a56e4adc7f2fe6a43c4fc44728f016d9d288

test:
  secret_key_base: ca514fe9ba027e95070a259686d22d1ecb156bdb7f52503d72ef0fc0f0df5b1829e7a5dfa7b4e253ad8eac3d4ffb97f87bbf712f84f5fe111e20f685fc4b1962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
